In [2]:
import sys
import numpy as np
import pandas as pd 
import matplotlib as mpl
import sklearn

In [ ]:
# 팬시
# array[ [0, 2], 0:2]

# 불린
# array [ array > 5]  # bool값의 index만 return되어 filtering
# array2 = array [ array > 5]


In [3]:
org_array = np.array( [ 3,1,9,5])
org_array

array([3, 1, 9, 5])

In [5]:
sort_array1 = np.sort(org_array)
sort_array1

array([1, 3, 5, 9])

In [7]:
# return None
sort_array2 = org_array.sort()
sort_array2

In [9]:
sort_array_desc = np.sort(org_array)[::-1]
sort_array_desc

array([9, 5, 3, 1])

### 2차원

#### sort

In [4]:
array2d = np.array( [[ 8, 12],
                     [ 7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis =0)
sort_array2d_axis0

array([[ 7,  1],
       [ 8, 12]])

In [5]:
sort_array2d_axis0 = np.sort(array2d, axis =1)
sort_array2d_axis0

array([[ 8, 12],
       [ 1,  7]])

#### argsort

In [6]:
org_array = np.array( [ 3, 1, 9, 5])

In [8]:
sort_indices = np.argsort(org_array)
sort_indices

array([1, 0, 3, 2], dtype=int64)

In [9]:
sort_indices_desc = np.argsort(org_array)[::-1]
sort_indices_desc

array([2, 3, 0, 1], dtype=int64)

In [10]:
name_array = np.array ( [ 'jonh', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78,95,84,98,88])

In [11]:
sort_indices = np.argsort(score_array)
sort_indices

array([0, 2, 4, 1, 3], dtype=int64)

In [12]:
name_array_sort = name_array[sort_indices]
score_array_sort = score_array[sort_indices]
print(name_array_sort)
print(score_array_sort)

['jonh' 'sarah' 'samuel' 'mike' 'kate']
[78 84 88 95 98]


### 선형대수

In [ ]:
dot_product = np.dot(A, B)

transpose_mat = np.transpose(A)